'use client';

import React, { useState, useMemo } from 'react';
import { Recipe } from '@/lib/game/recipes';
import { BraidCrossing, FlavorProfile, FusionResult } from '@/lib/quantum/braidTypes';
import { generateBloubAdvice, GhostCrossingHint } from '@/lib/quantum/bloubAdvisorEngine';
import { soundFx } from '@/lib/audio/synthAudio';
import { Lightbulb, ChevronDown, ChevronUp, Sparkles, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { BloubBot } from './BloubBot';

interface ChefCompanionProps {
  recipe: Recipe;
  currentFlavors: FlavorProfile;
  successEnergy: number; // 0 to 1
  crossings: BraidCrossing[];
  decoherenceGlitch: number; // 0 to 1
  isCooking: boolean;
  lastFusionResult: FusionResult | null;
  stabilizerLevel: number;
  credits?: number;
  onShowGhostMove?: (hint: GhostCrossingHint | null) => void;
  activeGhostMove?: GhostCrossingHint | null;
}

export function ChefCompanion({
  recipe,
  currentFlavors,
  successEnergy,
  crossings,
  decoherenceGlitch,
  isCooking,
  lastFusionResult,
  stabilizerLevel,
  credits = 0,
  onShowGhostMove,
  activeGhostMove,
}: ChefCompanionProps) {
  const [isMinimized, setIsMinimized] = useState(false);
  const [customTip, setCustomTip] = useState<string | null>(null);
  const [tipIndex, setTipIndex] = useState(0);

  // Intelligent Contextual Advice generated by Bloub Quantum Advisor Engine
  const liveAdvice = useMemo(() => {
    return generateBloubAdvice({
      recipe,
      currentFlavors,
      successEnergy,
      crossings,
      decoherenceGlitch,
      isCooking,
      lastFusionResult,
      stabilizerLevel,
      credits,
    });
  }, [
    recipe,
    currentFlavors,
    successEnergy,
    crossings,
    decoherenceGlitch,
    isCooking,
    lastFusionResult,
    stabilizerLevel,
    credits,
  ]);

  // General culinary & quantum wisdom tips
  const WISDOM_TIPS = useMemo(
    () => [
      'In topological quantum cooking, your recipe depends on the braid geometry, not minor strand vibrations!',
      'An Over-weave is a braiding operator σ; an Under-weave is its inverse σ⁻¹.',
      'Fibonacci anyons satisfy τ ⊗ τ = 1 ⊕ τ. They are universal for topological quantum computation!',
      'Need more credits? Build longer complex braids to compound your Umami Multiplier!',
      'Cryo-Stabilizers in the Pantry reduce thermal decoherence so your dishes never burn into identity particles.',
      'Check the Scientist Portal at the top right to inspect the exact R and F unitary matrices!',
    ],
    []
  );

  const handleNextTip = () => {
    soundFx.playMascotChirp(Math.floor(Math.random() * 5));
    const nextTip = WISDOM_TIPS[tipIndex % WISDOM_TIPS.length];
    setTipIndex((prev) => prev + 1);
    setCustomTip(nextTip);
  };

  const handleToggleGhostMove = (hint: GhostCrossingHint) => {
    soundFx.playMascotChirp(1);
    if (activeGhostMove?.lane === hint.lane && activeGhostMove?.isOver === hint.isOver) {
      onShowGhostMove?.(null);
    } else {
      onShowGhostMove?.(hint);
    }
  };

  const activeText = customTip || liveAdvice.text;
  const isPreviewing = Boolean(
    liveAdvice.ghostMove &&
      activeGhostMove?.lane === liveAdvice.ghostMove.lane &&
      activeGhostMove?.isOver === liveAdvice.ghostMove.isOver
  );

  return (
    <aside
      aria-label="Bloub Sous-Chef Companion"
      className="fixed bottom-4 right-4 z-40 flex flex-col items-end select-none pointer-events-none"
    >
      <div className="pointer-events-auto flex flex-col items-end max-w-sm sm:max-w-md">
        {/* Speech Bubble (when expanded) */}
        {!isMinimized && (
          <div className="relative mb-3 rounded-2xl border border-slate-200 dark:border-[#393939] bg-white/95 dark:bg-[#161616]/95 backdrop-blur-md p-4 shadow-2xl transition-all animate-in fade-in slide-in-from-bottom-2 text-xs">
            {/* Header / Identity & Status Badge */}
            <div className="flex items-center justify-between gap-2 border-b border-slate-100 dark:border-[#2b2b2b] pb-2 mb-2">
              <div className="flex items-center gap-2">
                <span className="flex h-2.5 w-2.5 rounded-full bg-[#009d9a] animate-pulse" />
                <span className="font-bold text-sm text-slate-800 dark:text-[#f4f4f4] tracking-tight">
                  Bloub
                </span>
                <span className="rounded bg-[#8a3ffc]/15 px-1.5 py-0.5 text-[9px] font-mono font-bold text-[#8a3ffc] dark:text-[#be95ff]">
                  Sous-Chef AI
                </span>
                {!customTip && (
                  <Badge variant={liveAdvice.badgeVariant} className="text-[10px] px-1.5 py-0 font-mono">
                    {liveAdvice.badgeLabel}
                  </Badge>
                )}
              </div>

              <div className="flex items-center gap-1">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleNextTip}
                  className="h-6 px-2 text-[10px] text-slate-500 hover:text-[#8a3ffc] hover:bg-[#8a3ffc]/10 cursor-pointer"
                  title="Cycle quantum trivia & tips"
                >
                  <Lightbulb className="h-3 w-3 mr-1 text-[#f1c21b]" />
                  Tip Me
                </Button>

                <button
                  onClick={() => setIsMinimized(true)}
                  className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 p-1 rounded transition-colors cursor-pointer"
                  title="Minimize Sous-Chef"
                  aria-label="Minimize Bloub Sous-Chef"
                >
                  <ChevronDown className="h-4 w-4" />
                </button>
              </div>
            </div>

            {/* Bubble Tip Content */}
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed font-sans pr-1 text-[13px] mb-2.5">
              {activeText}
            </p>

            {/* Interactive Action Row (Predictive One-Click Ghost Move) */}
            {!customTip && liveAdvice.ghostMove && onShowGhostMove && (
              <div className="flex items-center gap-2 pt-1 border-t border-slate-100 dark:border-[#2b2b2b]">
                <Button
                  size="sm"
                  onClick={() => handleToggleGhostMove(liveAdvice.ghostMove!)}
                  className={`h-6 text-[11px] font-bold px-2.5 rounded-md transition-all cursor-pointer ${
                    isPreviewing
                      ? 'bg-[#009d9a] text-white hover:bg-[#007d79]'
                      : 'bg-[#8a3ffc] text-white hover:bg-[#6929c4]'
                  }`}
                >
                  {isPreviewing ? (
                    <>
                      <Check className="h-3 w-3 mr-1" />
                      Showing Ghost Path
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-3 w-3 mr-1" />
                      Preview Move on Loom
                    </>
                  )}
                </Button>
                <span className="text-[10px] font-mono text-slate-400">
                  Lane {liveAdvice.ghostMove.lane} ({liveAdvice.ghostMove.isOver ? 'Over' : 'Under'})
                </span>
              </div>
            )}

            {/* Bubble Tail pointer pointing directly to Bloub center */}
            <div className="absolute -bottom-2 right-16 h-3 w-3 rotate-45 border-r border-b border-slate-200 dark:border-[#393939] bg-white dark:bg-[#161616]" />
          </div>
        )}

        {/* The Avatar Dock & Trigger */}
        <div className="flex items-center gap-2">
          {isMinimized && (
            <button
              onClick={() => setIsMinimized(false)}
              className="flex items-center gap-2 rounded-full border border-slate-700 bg-white/95 dark:bg-[#161616]/95 px-3.5 py-2 text-xs font-semibold text-slate-800 dark:text-white shadow-xl backdrop-blur-md hover:border-[#8a3ffc] transition-all cursor-pointer group"
            >
              <span className="flex h-2 w-2 rounded-full bg-[#009d9a] animate-pulse" />
              <span>Bloub</span>
              <ChevronUp className="h-3.5 w-3.5 text-slate-400 group-hover:text-[#8a3ffc]" />
            </button>
          )}

          {/* Pure Authentic Bloub Mascot with Transparent Background & Dynamic Expressive Faces */}
          <div
            aria-label="Bloub the Sous-Chef Companion"
            className="relative flex items-center justify-center select-none"
          >
            <BloubBot
              expression={liveAdvice.expression}
              size={135}
              followCursor={true}
            />
          </div>
        </div>
      </div>
    </aside>
  );
}
